### ISSUE TITLE
Erreur récupération des données

### ISSUE THREAD

**Issue by OnilDu39** [max5962/essence#2]
Bonjour,

J'obtiens le message d'erreur **"Failed to download new data, will be retry"**

Après investigation, vous téléchargez le fichier "**https://donnees.roulez-eco.fr/opendata/jour**". Or ce fichier n'existe pas, il faut rajouter le jour à la fin de l'URL, tel que : **https://donnees.roulez-eco.fr/opendata/jour/20201128** par exemple.

Si je comprends bien, votre intention est plutôt de télécharger le fichier **https://donnees.roulez-eco.fr/opendata/instantane** non ?

Je sais que cette lib est utilisée dans l'intégration PrixCarburant pour Home Assistant, qui du coup chez moi ne fonctionne pas. J'ai vu des personnes sur https://forum.hacf.fr/t/recuperer-les-prix-de-carburants/644 pour qui cela fonctionnait, je suis donc très surpris. 

Merci d'avance

**Comment by clemalex824** [comment]
@YoannNicod  : https://www.prix-carburants.gouv.fr/rubrique/opendata/
Le lien est bon.
Si tu le colle dans ton navigateur préféré, tu verras que le fichier archive cible est celui du jour courant.
L'erreur est ailleurs.

**Comment by OnilDu39** [comment]
Non j'ai retracé ce qu'il se passe.
L'erreur vient précisément du fait que le fichier n'existe pas.

Ce qui est très étrange, c'est que ça marche PARFOIS. Par exemple, là, on est le 30/11/2020 à 22h37, et quand je clique sur https://donnees.roulez-eco.fr/opendata/jour, ça fonctionne, ça télécharge bien le fichier. Mais j'ai eu plein d'occasions lors desquelles le site m'envoyait une erreur 404.

Donc ça explique pourquoi l'intégration fonctionne DE TEMPS EN TEMPS, mais échoue le reste du temps.
J'ai écrit au support de https://www.prix-carburants.gouv.fr/ qui m'ont répondu que ce lien doit être utilisé en ajoutant le jour à la fin de l'URL.

Je réessaierai demain de trouver un moment où le lien ne marche pas. Mais je suis sûr et certain que je l'ai déjà rencontré manuellement (en fait, c'est même la première fois ce soir que le lien fonctionne quand j'y vais manuellement).

**Comment by OnilDu39** [comment]
Aujourd'hui, 01/12/2020 à 11h29, le lien https://donnees.roulez-eco.fr/opendata/jour donne :
![image](https://user-images.githubusercontent.com/2385767/100729023-8bfcac00-33c8-11eb-8c5c-152d61e63e27.png)

**Comment by clemalex824** [comment]
et le 2020-12-02 à 00:10 ça donne (avec les recommandations du support...) : 
![image](https://user-images.githubusercontent.com/35152089/100807691-0e21ba80-3433-11eb-87b4-8b35400ae980.png)
![image](https://user-images.githubusercontent.com/35152089/100807631-f8ac9080-3432-11eb-9874-2032895ba59d.png)

Je pourrais comprendre que les données du jour ne sont pas disponibles à minuit, mais ceux de la veille, je ne comprends pas.

Il faudrait donc ne pas mettre à jour les entités si pas de données récupérées...

**Comment by OnilDu39** [comment]
Ah oui effectivement ça ne marche même pas avec le jour.
Pourquoi ne pas utiliser le lien https://donnees.roulez-eco.fr/opendata/instantane du coup ? Chez moi ça marche

**Comment by clemalex824** [comment]
Faudrait surtout ouvrir un ticket chez l'open data du gouvernement pour qu'il règle le soucis.

Pour le fait d'utiliser une autre ressource, pourquoi ne pas faire une PR plutôt ?

Peut être que l'utilisation de la ressource jour est historique et à l'époque pas de ressource instantanée..

**Comment by OnilDu39** [comment]
J'ai recontacté le support en expliquant mieux, ils m'ont répondu :

> Nous avons effectivement un problème technique en cours d'identification et de correction. Nous vous informerons lorsque le lien sera rétabli.

Dans tous les cas il suffirait de remplacer "jour" par "instantane" dans le code pour que cela fonctionne (si les fichiers sont bien similaires). Ce serait d'ailleurs plus logique d'un point de vue sémantique.

Je n'ai jamais fait de PR je ne sais pas comment ça fonctionne.

**Comment by clemalex824** [comment]
> Je n'ai jamais fait de PR je ne sais pas comment ça fonctionne.

C'est le moment de s'y mettre alors ! 😁😇

Ma première remonte à moins d'un mois, et ce n'est pas si compliqué (fork, modification, reviens ici dans l'onglet PR et suit les instructions) 

D'accord sur le fait de prendre instantané au lieu de jour...(a moins que jour soit le reflet d' instantané dans la journée.. A tester)

Reviens sur forum.hacf.fr pour donner des nouvelles (celles du support j'entends 👍)

**Comment by OnilDu39** [comment]
PR créée

**Comment by OnilDu39** [comment]
Bon heureusement le support a fait son travail et a corrigé le problème de leur côté. Problème résolu.
